baseURL = "https://christian-kento-rasmussen.github.io/US-Congress-Twitter-Behavior/"
title = "US Congress Twitter Behavior"
description = "US Congress Twitter Behavior description"
relativeURLs = true
theme = "theme"  
[params] 
    authors = ["christian", "Mathias", "Benjamin"]
    notebook = "/explainer-notebook.html"
    data = "https://github.com/alexlitel/congresstweets/tree/master/data"
    github = "https://github.com/christian-kento-rasmussen/US-Congress-Twitter-Behavior"
    [[params.nav]]
        label = "Dataset"
        link = "/data-description"
    [[params.nav]]
        label = "Network"
        link = "/network-structure"
    [[params.nav]]
        label = "Communities"
        link = "/community-structure"
    [[params.nav]]
        label = "Text"
        link = "/congressional-communities"
    [[params.nav]]
        label = "Evolution"
        link = "/evolving-dynamics"

